#!/usr/bin/env python
# -*- coding:utf-8 -*-

from __future__ import print_function, absolute_import

import click
import click_completion

click_completion.init()

cmd_help = """Shell completion for click-completion

Available shell types:

\b
  %s

Default type: auto
""" % "\n  ".join('{:<12} {}'.format(k, click_completion.shells[k]) for k in sorted(click_completion.shells.keys()))


@click.group(help=cmd_help)
def completion():
    pass


@completion.command()
@click.argument('shell', required=False, type=click_completion.DocumentedChoice(click_completion.shells))
def show(shell):
    """Show the click-completion completion code"""
    click.echo(click_completion.get_code(shell))


@completion.command()
@click.option('--append/--overwrite', help="Append the completion code to the file", default=None)
@click.argument('shell', required=False, type=click_completion.DocumentedChoice(click_completion.shells))
@click.argument('path', required=False)
def install(append, shell, path):
    """Install the click-completion completion"""
    shell, path = click_completion.install(shell=shell, path=path, append=append)
    click.echo('%s completion installed in %s' % (shell, path))


if __name__ == "__main__":
    completion()
